### PR TITLE
Fix #61: Increase dependency visibility

### LINKED ISSUE #61: Ktlint won't compile with version 0.3.0
I was trying to [update the sarif4k dependency in Ktlint](https://github.com/pinterest/ktlint/pull/2039) from version `0.2.0` to `0.3.0`. It however results in compilation errors below on the `ktlint-cli-reporter-sarif`:
```
> Task :ktlint-cli-reporter-sarif:compileKotlin FAILED
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.github.detekt.sarif4k.Level.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
    class io.github.detekt.sarif4k.Version.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
Adding -Xextended-compiler-checks argument might provide additional information.


Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.github.detekt.sarif4k.Level.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
    class io.github.detekt.sarif4k.Version.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
Adding -Xextended-compiler-checks argument might provide additional information.
```

Do you have any idea how to resolve?

### PR DESCRIPTION
**Pull request by TWiStErRob**
Fixes #61

### CODE REVIEW

**Comment by TWiStErRob** [comment]
Confirmed fix in ktlint with `publishToMavenLocal`:
image

**Review by cortinico — APPROVED** [review]
