### ISSUE TITLE
Ktlint won't compile with version 0.3.0

### ISSUE THREAD

**Issue by paul-dingemans** [detekt/sarif4k#61]
I was trying to [update the sarif4k dependency in Ktlint](https://github.com/pinterest/ktlint/pull/2039) from version `0.2.0` to `0.3.0`. It however results in compilation errors below on the `ktlint-cli-reporter-sarif`:
```
> Task :ktlint-cli-reporter-sarif:compileKotlin FAILED
e: Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.github.detekt.sarif4k.Level.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
    class io.github.detekt.sarif4k.Version.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
Adding -Xextended-compiler-checks argument might provide additional information.


Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class io.github.detekt.sarif4k.Level.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
    class io.github.detekt.sarif4k.Version.Companion, unresolved supertypes: kotlinx.serialization.KSerializer
Adding -Xextended-compiler-checks argument might provide additional information.
```

Do you have any idea how to resolve?

**Comment by cortinico** [comment]
cc @chao2zhang

**Comment by TWiStErRob** [comment]
Hmm 🤔
```shell
github-ktlint$ gradlew :ktlint-cli-reporter-sarif:dep > deps.txt
```
![image](https://github.com/detekt/sarif4k/assets/2906988/a17de54c-fcac-49b2-b37c-7faad2d2b6fc)

Probably the result of going multiplatform: https://github.com/detekt/sarif4k/pull/6

Tried this, but no change:
```diff
-sarif4k = "io.github.detekt.sarif4k:sarif4k:0.2.0"
+sarif4k = "io.github.detekt.sarif4k:sarif4k-jvm:0.3.0"
```

As a quick workaround you re-add the missing dependency to `ktlint-cli-reporter-sarif`.

**Comment by TWiStErRob** [comment]
Quick decompile of `sarif4k-jvm-0.3.0.jar` shows:
```
package io.github.detekt.sarif4k;
import kotlinx.serialization.KSerializer;
import kotlinx.serialization.Serializable;

@Serializable(with = Companion.class)
public enum Level {
   public static final Companion Companion = new Companion((DefaultConstructorMarker)null);

   public static final class Companion implements KSerializer<Level> {
```
which means this dependency should be `api`.

**Comment by paul-dingemans** [comment]
Problem is indeed solved with 0.4. Tnx.

**Comment by chao2zhang** [comment]
Thank you for verifying!
